### ISSUE TITLE
Improve Splash Screen Loading

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#489] opened 2019-02-04 17:13 UTC
## Background
Splash screen is loading slowly on opening the App

>@Brad are we pre-loading all the event images? Currently in even moderate connectivity when you open the app it takes forever to switch from the blank white screen to the splash screen and into the app, wondering if it's just the app ui a

**Comment by jwietelmann** [comment] 2019-02-05 15:19
I'm currently shuffling some things around so that more startup stuff happens in parallel while the splash screen is playing. I should probably ask Zach to clarify what he means since, for me, what I am observing is that it's the time _after_ the splash screen that feels weird. (He described it as blank white _before_, and I'm not sure if he's having a different experience or misstated the problem.) In any case, I think there are things that I can do to make it smoother to boot into the first interactive screen, and that's going to be a good thing. If getting the splash video itself loaded is the actual bottleneck he wants fixed, that's just an extra thing to deal with on top. (In which case, maybe the solution there involved further compressing the splash video?)

**Comment by jwietelmann** [comment] 2019-02-05 15:24
More context around doing more things in parallel: I'm making sure that the splash sticks around until assets are preloaded. I'm preloading images and fonts in parallel. What I'm going to add to what loads in parallel next is: Pulling the user's auth token from storage and logging them in they're still valid. Currently we don't start the process doing that until after the asset loading and splash is complete, and we can speed up the boot by starting the token retrieval and auth check from the outset.

**Comment by jwietelmann** [comment] 2019-02-05 20:50
Note: It currently takes ~150-250ms to go from start to splash.

**Comment by jwietelmann** [comment] 2019-02-05 21:20
I think my changes actually made it worse. I'm going to have to try a different tactic.

**Comment by jwietelmann** [comment] 2019-02-05 21:37
In dev mode, the app takes 100-150ms from boot to get to the splash screen. After several tests, what I can say is that neither preloaded images nor fonts are having an substantive difference on this boot time. I can remove every image and every font from preloading, and the results stay fairly consistent in that 100-150ms range.

**Comment by jwietelmann** [comment] 2019-02-05 21:58
Currently interrogating Zach to see if the issue is actually the OTA updates downloading: https://docs.expo.io/versions/latest/guides/configuring-ota-updates/

**Comment by jwietelmann** [comment] 2019-02-06 15:33
This is replaced by #494 which more accurately describes the root of the problem. Closing.

**Closed by jwietelmann** 2019-02-06 15:33 UTC
Labels: in progress, points:8
