### ISSUE TITLE
Doorperson - Clicking the last successful scan pill overlaying the scanner view should display a list of all scanned/checked-in tickets on that device

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#508] opened 2019-02-13 20:01 UTC
Depends on #507 

The pill will show the last successful scan info.

The last pill will show
- Persons name
- Ticket Type
- Time Since Scanned ("1 mins ago", "35 seconds ago", "1 hour 35 minutes ago")

**Comment by jwietelmann** [comment] 2019-02-14 17:34
From Slack conversation:

* A given ticket can only successfully be scanned once, so there will only be one timestamp per ticket.
* We are going to keep track of this _on the device_. (There is no API data for this.)
* It will only show successful scans that happened _on that device_. That is actually more or less the point. The door person wants to know "Oh, I just double-scanned this myself in the last minute" and that sort of thing.

**Comment by jwietelmann** [comment] 2019-02-14 18:39
An approved alternative: Just show that bit of info on the pill.

**Comment by jwietelmann** [comment] 2019-02-14 21:10
I went with the alternative for now because I know there are some UX things coming up soon, and this Zach-approved quick fix solves the problem for the door person more simply.

**Comment by jwietelmann** [comment] 2019-02-15 16:13
Awaiting review from @daybreaker

**Comment by Mcscott142** [comment] 2019-02-15 19:07
@jwietelmann getting an error on Scan. 

Reproduction Steps:
1) Purchase Ticket to `Warped Study` Event
2) On another device scan the purchased ticket
2) Auto Scan works but I do gan error message for 'Internal Error with Tari Platform` 
3) Manual Scan throws an exception 

```
[13:02:07] Invariant Violation: Invariant Violation: Invariant Violation: Invariant Violation: Text strings must be rendered within a <Text> component.

This error is located at:
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in TouchableHighlight (at eventScanner.js:145)
    in TicketDetailsPill (at eventScanner.js:353)
    in RCTView (at View.js:44)
    in BottomTab (at eventScanner.js:402)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in EventScanner (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:58)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:44)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at accountStack.js:40)
    in Consumer (created by Subscribe)
    in Subscribe (at accountStack.js:38)
    in accountsStackWithStore (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in ResourceSavingScene (at createBottomTabNavigator.js:108)
    in RCTView (at View.js:44)
    in ScreenContainer (at createBottomTabNavigator.js:98)
    in RCTView (at View.js:44)
    in TabNavigationView (at createTabNavigator.js:178)
    in NavigationView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (created by App)
    in Provider (created by Consumer)
    in Consumer (created by Provider)
    in Provider (at App.js:93)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
```

**Comment by jwietelmann** [comment] 2019-02-15 19:18
> Internal Error with Tari Platform

Sounds like probably an API team problem.

> Manual Scan throws an exception

Sounds like I need to handle the API error better.

**Comment by jwietelmann** [comment] 2019-02-15 19:52
I found and fixed the InvariantViolation thing, and I verified that the API is generating the other error. I filed an issue with the API team here: https://github.com/big-neon/bn-api/issues/1041

**Comment by jwietelmann** [comment] 2019-02-15 19:53
@zmelamed The change has been made, but we're having trouble redeeming tickets right now because of the API.

**Comment by zmelamed** [comment] 2019-02-18 19:07
I believe these issues have been resolved

**Comment by Mcscott142** [comment] 2019-02-19 20:49
Getting errors when opening a Ticket in the wallet. Opening bug, marking Blocked

**Comment by Krakaw** [comment] 2019-02-20 13:05
Resolved. Tickets purchased on Friday for a few hours had this crazy issue pop up.

**Comment by Mcscott142** [comment] 2019-02-20 15:03
Looks good, moving to UAT. Updated AC with Approved alternative from comments.

**Closed** 2019-03-06 23:28 UTC
Labels: UAT
