### ISSUE TITLE
Attendee - My Tickets - Past Tickets

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#255] opened 2018-11-07 20:13 UTC
## Background 
After I have attended an event I want to be able to see that history. 

## Scenario: A user views past events when they navigate to My Tickets
- [ ] When I select Past 
- [ ] Then I see a list of events I have attended

### Mock 
![big_neon](https://user-images.githubusercontent.com/6877299/48158086-272d0100-e297-11e8-8486-3436ec5d6561.png)

**Comment by brittanygay** [comment] 2018-11-29 20:56
Just an FYI, the design is stubbed out for this, we just need to add functionality.

**Comment by daybreaker** [comment] 2018-11-30 16:33
Will they be able to open this up to view ticket info, or is this going to be a static card?

If its static, thats better, since I only need to update the index to tun off the navigate('TicketShow') for these.   If they can open it back up, to see individual tickets, we'd need to redesign it to remove the blank space where the QR code wouldve been.

(I have the same question for transferred tickets - if it should be static on the index, or able to be opened up into the show view)

My vote goes to not allowing past or transferred to be touched into the show view.

**Comment by Mcscott142** [comment] 2018-11-30 17:10
@daybreaker I believe in some future version the QR code will be removed and replaced with some other info about the event. For now roll with:

> My vote goes to not allowing past or transferred to be touched into the show view.

**Comment by zmelamed** [comment] 2018-11-30 17:17
Is it just as easy to leave the square where the qr code is is just empty if the tickets in past or transferred. The issue is it’ll feel broken if a user  tries to click on the cards in past and transferred and nothing happens.

If that’s significantly more work, then just showing a system dialog that says “This event has ended.” Or “These tickets were transferred” would be my next vote. Then if that’s also a project we can just disable the click all together for right now.

**Comment by daybreaker** [comment] 2018-12-05 20:09
It would probably just take a little design work to make the space where the QR code was to remain empty but still have a static height. @brittanygay

**Comment by brittanygay** [comment] 2018-12-05 20:35
How about we add an Empty state in place of where the QR code was to either say "This event has ended" or "These tickets have been transferred"? That way it's not just a blank space and instead it's informing the user. This should be an easy design update on my part.

**Comment by jwietelmann** [comment] 2018-12-13 18:04
I can't buy tickets for a past event, and my users only have tickets for future events. Blocked until we can actually get the API to give us some past events.

**Comment by Mcscott142** [comment] 2018-12-14 14:46
@jwietelmann This may be a bug in itself but if you buy a ticket to the `Event Going` event on staging it will show up in your past tickets.

**Closed** 2019-01-03 14:19 UTC
Labels: QA, points:3
