### ISSUE TITLE
Error when adding tickets

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#728] opened 2019-04-18 19:12 UTC
Click the + on a ticket really quickly you'll see the error

**Comment by iamjoshfrank** [comment] 2019-05-06 17:55
If this is still occurring, I'd say work it!

**Comment by bryanjos** [comment] 2019-05-06 18:03
I created an issue from a slack comment and waited for details. Nothing came about

**Comment by iamjoshfrank** [comment] 2019-05-06 18:09
So you've tried to reproduce and haven't been successful? If that's the case, mark it blocked and assign Zach.

**Comment by jpatricknola** [comment] 2019-05-10 15:59
@bryan where in the flow of the app does this error occur?

**Comment by bryanjos** [comment] 2019-05-10 16:02
Haha, I don't know. Not many details were given. @Krakaw do you have more details on this specific bug?

**Comment by jpatricknola** [comment] 2019-05-10 16:02
![Screen Shot 2019-05-10 at 11.01.33 AM.png](https://images.zenhubusercontent.com/5cbf376ce0d3d508934b139c/1e69d7c2-2a87-4002-a3ac-fbf0ce61b6c6)

Im on this page but have been able to recreate the error by clicking + and - repeatedly it appears to work fine

**Comment by Krakaw** [comment] 2019-05-10 16:09
It looks like it has been fixed by disabling the `+` button once you hit the ticket_limit which wasn't happening before.

**Comment by jpatricknola** [comment] 2019-05-10 16:12
Right on thanks @Krakaw.   I will close and resolve this issue then

**Closed** 2019-05-10 16:16 UTC
Labels: blocked, bug
