### ISSUE TITLE
Attendee - Transfer Ticket - Accept Ticket transfer via shared link

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#421] opened 2018-12-26 20:49 UTC
## Background 
The initial functionality for ticket transfers will just be transferring via a phone number or email. We'll implement QR codes and more bells and whistles later. 

Via Slack from @zmelamed 
>So ticket transfers does look pretty straightforward to send directly through the API. If we can easily access the address book (I have to imagine there's an expo plugin for that) you just need to run this:

Snippet from BN API:
```
 Bigneon()
            .tickets.transfer.send({
                ticket_ids: ticketIds,
                validity_period_in_seconds: 60 * 60 * 24, //TODO make this config based
                email_or_phone: emailOrCellphoneNumber
            })
            .then(response => {
                this.setState({ isSubmitting: false }, () => {
                    this.onClose();

                    notification.show({
                        message: "Ticket transfer link sent.",
                        variant: "success"
                    });
                });
            })
            .catch(error => {
                this.setState({ isSubmitting: false });
                console.error(error);
                notification.showFromErrorResponse({
                    error,
                    defaultMessage: "Send tickets via email or phone failed.",
                    variant: "error"
                });
            });
```

## Scenario: A user accepts ticket transfer via link
Given I have received a text or email with a transfer link
- [ ] When I click the link
- [ ] Then I can accept or decline a ticket transfer

**Comment by jwietelmann** [comment] 2018-12-31 17:50
Isn't this a website/API thing that doesn't involve us? Once #420 happens, the rest is handled by web servers sending emails out.

**Comment by Mcscott142** [comment] 2018-12-31 19:33
I was under the impression that we needed to confirm the transfer from the App to accept the tickets, but I could be wrong. If it looks like all of that is handled on the Web/API side then feel free to close this one.

**Comment by jwietelmann** [comment] 2019-01-02 20:10
Confirmed the email sends you to the web site, but after signing up I get logged in with a "Business process error" message.

**Comment by jwietelmann** [comment] 2019-01-02 21:45
After thinking about this a little, rather than get rid of this issue I think I'm just going to mark it blocked and say that when the web is fixed, we should use this ticket to check that the sender's and recipient's respective mobile apps properly reflect that the tickets were transferred, given that mobile data pulls rather than pushes.

Stuff like:

* I'm already looking at my list of ticketed events, and I tap on an event where I have transferred away all my tickets: What happens?
* Figuring out how to populate the transfers sub-tab. (We need API support because right now its data does not really tell us that the ticket has a pending transfer.)

**Comment by Mcscott142** [comment] 2019-01-08 15:56
The web is still having issues with Ticket Transfers. We have an Outstanding PR https://github.com/revelrylabs/bn-mobile-react/pull/427 for transferring tickets. When on that branch, each time a ticket transfer is initiated the email is sent but Accepting the transfer via email drops an error:

![fullscreen_1_8_19__9_53_am](https://user-images.githubusercontent.com/6877299/50842091-a7212700-132b-11e9-9091-f1a03ad9d2b1.png)

cc @Krakaw @zmelamed

**Comment by Mcscott142** [comment] 2019-01-10 16:19
Unblocking, issues on Web have been resolved.

**Closed** 2019-01-23 21:46 UTC
Labels: SCORE, UAT
