### ISSUE TITLE
Invalid Date Time when “Doors Open” time not present (use show start time)

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#334] opened 2018-12-04 18:20 UTC

**Comment by jwietelmann** [comment] 2018-12-14 16:45
@daybreaker do you have more info about this? like an example of where to find it in the wild?

**Comment by jwietelmann** [comment] 2018-12-17 15:38
Is this a duplicate of #385?

**Comment by Mcscott142** [comment] 2018-12-17 18:16
Closing this one and 385, can't reproduce issues 385 or 334.

**Closed by Mcscott142** 2018-12-17 18:16 UTC
Labels: Up Next, blocked, bug
