### ISSUE TITLE
As a Doorperson, it is hard for me to press the "Guest List" button

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#600] opened 2019-03-11 13:29 UTC
## Description
When a Doorperson tries to click on the "Guest List" button, it can be hard to click. The belief is that that the TouchableHighlight wraps the text and not the entire button area. Meaning someone has to click the text exactly for it to recognize a press.

## Steps to Reproduce
Provide steps to reproduce the issue you encountered.

- [ ] Login as a Doorperson
- [ ] Go to the Doorperson tools
- [ ] Select an event
- [ ] On the scanner screen, try to click on "Guest List"
- [ ] **Observe**: It is hard to click on

## Platform/Device/Browser Information
Please provide platform, device , and browser (when applicable) that you were using when you encountered the issue.

- [ ] Platform: Android (not sure if bug is on iOS as well)

**Comment by bryanjos** [comment] 2019-03-11 16:19
I think this may be an issue with the position style being absolute, but I'm not 100% positive on that. Will let @brittanygay take a look when she has a chance

**Comment by brittanygay** [comment] 2019-03-11 16:29
Pulling this in to look into today

**Comment by brittanygay** [comment] 2019-03-11 19:57
I'm testing on iOS and it's definitely not a bug there, at least when I test on devices on the Simulator and on my iPhone 6s. I don't have an Android with me but I am trying to put in a fix today and going to test first thing tomorrow once I have access to an Android.

**Comment by Mcscott142** [comment] 2019-03-13 14:24
Passes on Galaxy S5. Moving to UAT. Will grab S6 when it comes back around to the office.

**Closed** 2019-03-28 22:29 UTC
Labels: UAT, bug, design
