### ISSUE TITLE
Android - Ticket Transfer - QR cut off on Android

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#453] opened 2019-01-21 21:03 UTC
The Transfer QR code is cut off on Android. Using Galaxy On5 LTE. 

![screenshot_20190121-145845](https://user-images.githubusercontent.com/6877299/51498825-9f329f80-1d8d-11e9-85c4-db00b51f40cb.png)

**Comment by jwietelmann** [comment] 2019-01-21 22:11
@Mcscott142 Can you consolidate this with #452? I think they're caused by the same alignment problem and just manifesting differently on iOS vs Android.

**Comment by brittanygay** [comment] 2019-01-21 22:31
Looks like this is definitely a design bug. I can take a look into this along with #452

**Comment by brittanygay** [comment] 2019-01-22 19:33
Pulling this in to work on next

**Comment by brittanygay** [comment] 2019-01-22 20:18
The bug fix in #452 also fixed this issue. Here's a screenshot of what it looks like on Android now:
![Screenshot_20190122-140920.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56154cf43bdd627e00d5004a/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd791775216455f77b29d7b36af3006b1300051bff054a5556f9ab8f2fa0e03b74de0d0fead8385f74c76f19acb88018bf13a632c91edbe2e3d7158abd7f37ed998e48341f001c81fe553da29e49cf5cf559ac.png)

Putting this into review and then moving to QA once my PR for #452 is merged

**Comment by brittanygay** [comment] 2019-01-22 20:22
PR is now merged. This will be ready for QA after the next deploy

**Comment by Mcscott142** [comment] 2019-01-23 21:59
Waiting on some software updates before I QA this one

**Closed** 2019-01-31 18:09 UTC
Labels: UAT, bug
