### ISSUE TITLE
App Crashing / Reloading w/ Last prod build (42)

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#664] opened 2019-03-25 16:11 UTC
See Slack thread for more details: https://revelry-public.slack.com/archives/CC1659FUZ/p1553290776031500

- [ ] Reports of the Application crashing when Images were loading on the Discover Page

- [ ] Bryan reported intermittent app reloads on Android

**Comment by Mcscott142** [comment] 2019-03-25 16:12
deploying to stage now for reproduction of errors

**Comment by Mcscott142** [comment] 2019-03-25 16:23
Stage is deployed for Testing

**Comment by bryanjos** [comment] 2019-03-25 16:24
Debugging expo locally using production mode, I did manage to see a restart. This is all I got in the logs though:

```
[11:20:49] Unhandled promise rejection [Error: timeout of 3000ms exceeded]
[11:20:49] Unhandled promise rejection [Error: timeout of 3000ms exceeded]
[11:20:49] Unhandled promise rejection [TypeError: undefined is not an object (evaluating 'u.forEach')]
```

I got it around the transfer of tickets screen, but friday I didn't get there and it was restarting on the tickets screen the screen itself may not be the cause (or could be)

**Comment by bryanjos** [comment] 2019-03-25 16:26
Got the same again

```
[11:25:49] Unhandled promise rejection [Error: timeout of 3000ms exceeded]
```

**Comment by bryanjos** [comment] 2019-03-25 16:36
@Mcscott142 I have downloaded the beta (1.0.43) on android (google pixel) not been able to reproduce. I haven't seen any restarts yet.


@zmelamed are there any good reproducible steps to take to get the error?

**Comment by Mcscott142** [comment] 2019-03-25 16:41
@bryanjos it should be v45. Let me make sure you're on beta tester list.

**Comment by Mcscott142** [comment] 2019-03-25 16:47
@bryanjos I added you as Beta Tester with both bryan@revelry and bryanjos@gmail, you should be able to download latest v45.

**Comment by bryanjos** [comment] 2019-03-26 13:46
To recap from Slack. No one can reproduce anymore. We believe the issue is around API timeouts. There is an issue (#666) around it. We plan on deploying to production again today.

With that in mind, I'm going to close this issue.

**Closed by bryanjos** 2019-03-26 13:46 UTC
Labels: Up Next
