### ISSUE TITLE
As a doorperson after scanning a ticket and a random amount of time I get the following error

### ISSUE THREAD

**Issue by Krakaw** [revelrylabs/bn-mobile-react#787] opened 2019-05-17 10:30 UTC
This is happening in the production app
## Description
I scanned a valid ticket, after receiving success a random amount of time passes and this error appears. It seems to happen only on the first ticket that is scanned.

## Screenshots/Gifs
- ![Screenshot_20190517-122527](https://user-images.githubusercontent.com/41575888/57922072-307ad400-789f-11e9-90d7-d9d6d49caac7.jpg)

## Steps to Reproduce
Provide steps to reproduce the issue you encountered.

- [ ] I am logged in as this user `doorperson`:
- [ ] I am on this page: `Ticket scanning via camera`
- [ ] I performed these actions: `Scanned a ticket successfully, then waited`
- [ ] And saw this happen: `The above error`

## Platform/Device/Browser Information
Please provide platform, device , and browser (when applicable) that you were using when you encountered the issue.

i.e. *found on iOS iPhone 7+*, or *found on OSX High Sierra Chrome version 37.1*

- [ ] Platform: Android 9
- [ ] Device: OnePlus 5t
- [ ] Browser (if found on web application):

**Comment by jpatricknola** [comment] 2019-05-17 15:24
@Krakaw   
"It seems to happen only on the first ticket that is scanned."

Does this mean that we should create a new event in order to recreate the conditions for this error?

**Comment by Krakaw** [comment] 2019-05-17 19:36
I could replicate it by just closing the app and starting again, no need to create new events.

**Comment by zmelamed** [comment] 2019-05-17 23:03
Anything come of this or is this going to happen at tonights event?

**Comment by jpatricknola** [comment] 2019-05-18 16:20
@zmelamed

As best I can tell, this error is not occurring on the current develop branch.   I took the following steps:

- Logging in as superuser and going to account > doorperson 
- scanning a ticket (for the first time) and waiting 

I was unable to reproduce the error, testing on both android and iOS devices.    Tagging @bryanjos to take a look.

**Comment by iamjoshfrank** [comment] 2019-05-22 20:25
I experienced this bug on the Beta Android build, which I updated just an hour or so ago on my Samsung S7 Edge.

I wasn't specifically testing for this Issue so I wasn't screen recording at the time.

I can say it occurred the very first time I attempted scanning a ticket. Shortly after (seconds) the undefined message disappeared, I was able to re-point my camera at the ticket and successfully scan it. I did not have to exit the check-in mode or make any changes.

I'll see if I can screen record it at all.

**Comment by bryanjos** [comment] 2019-05-23 17:30
I can't reproduce this on the latest beta version or in development. Unless there are clearer steps to reproduce I say we close this one

**Comment by iamjoshfrank** [comment] 2019-05-23 17:32
Not yet.

It happened to me yesterday and I'm going to try to reproduce this afternoon.

No clues Sentry?

**Comment by bryanjos** [comment] 2019-05-23 17:37
Only thing that could be related is this, but without further info from sentry or the api there isn't anything I can see https://sentry.io/organizations/big-neon-5x/issues/1022708374/?project=1407235&query=is%3Aunresolved&statsPeriod=14d

**Comment by iamjoshfrank** [comment] 2019-05-23 22:20
Force closed the app and cleared my cache.

I was not able to reproduce this afternoon. Will try one more time tomorrow.

**Comment by iamjoshfrank** [comment] 2019-05-28 16:16
Since this hasn't been reported again in past 2 weekends, AND we're having troubles reproducing it, closing.

Can open a new Issue if it re-surfaces.

IF IT RESURFACES...please try to note the day and time so we can attempt to correlate it to any error reporting in Sentry.

**Closed by iamjoshfrank** 2019-05-28 16:17 UTC
Labels: Up Next, blocked, bug
