### ISSUE TITLE
My Tickets - Ticket View off - iPhone X

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#350] opened 2018-12-10 14:24 UTC
Ticket View off center for Iphone X. 

![image from ios 1](https://user-images.githubusercontent.com/6877299/49738361-d4a78180-fc54-11e8-956e-3cd116036c1a.png)

**Comment by brittanygay** [comment] 2018-12-11 16:01
Pulling this in to look into

**Comment by brittanygay** [comment] 2018-12-11 19:21
**Update**:
I can't seem to reproduce the issue, but then again I'm only able to test on the Simulator because I don't have access to an actual iPhone X. I can check to see if we have one in the office but I'm pretty sure we don't.

**Comment by brittanygay** [comment] 2018-12-11 19:45
**Update**:
I'll be able to borrow a coworkers iPhone X when I go into the office tomorrow. Putting this down until then and picking up another ticket from the backlog.

**Comment by brittanygay** [comment] 2018-12-12 19:01
I just tested on @gerardramos iPhone X and wasn't able to reproduce the issue/ it looks like the bug is already fixed. Moving this to QA (unless you would like to close this out @Mcscott142).

![IMG_2901.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56154cf43bdd627e00d5004a/125516c66e82c728ace21e0d46c1b9bd1cd0daf9deabf301b44fff9e2c4533317346f62926d1b52ee8167f005b5847f941585e16f4f98929a1b62e6c981e5ab38532022d8c6853beb2901eb60bbb258f4b83b2bd884bc9e83c22f5c6.JPG)

**Comment by Mcscott142** [comment] 2018-12-12 19:08
all good, go ahead and push it along.

**Closed** 2018-12-12 19:59 UTC
Labels: QA, bug
